with source as (select * from {{ source('raw', 'batting') }})
select
    game_pk,
    official_date::date          as game_date,
    team_id,
    player_id,
    player_name,
    position,
    batting_order,
    "atBats"::int                as at_bats,
    runs::int                    as runs,
    hits::int                    as hits,
    doubles::int                 as doubles,
    triples::int                 as triples,
    "homeRuns"::int              as home_runs,
    rbi::int                     as rbi,
    "baseOnBalls"::int           as walks,
    "intentionalWalks"::int      as intentional_walks,
    "strikeOuts"::int            as strikeouts,
    "hitByPitch"::int            as hit_by_pitch,
    "stolenBases"::int           as stolen_bases,
    "caughtStealing"::int        as caught_stealing,
    "groundIntoDoublePlay"::int  as gidp,
    "plateAppearances"::int      as plate_appearances,
    "totalBases"::int            as total_bases,
    "leftOnBase"::int            as left_on_base,
    "sacBunts"::int              as sac_bunts,
    "sacFlies"::int              as sac_flies,
    loaded_at
from source